### ISSUE TITLE
download doesn't work - domain download.rubackup.org is not resolvable 

### ISSUE THREAD

**Issue by CoolCold** [fdupoux/rubackup#1]
coolcold@ubuntu-12:~/tmp$ wget -O /dev/null -S 'http://download.rubackup.org/src/rubackup-0.1.1.tar.gz'
--2015-09-10 18:15:28--  http://download.rubackup.org/src/rubackup-0.1.1.tar.gz
Resolving download.rubackup.org (download.rubackup.org)... failed: Name or service not known.
wget: unable to resolve host address `download.rubackup.org'
coolcold@ubuntu-12:~/tmp$ host -vv download.rubackup.org
Trying "download.rubackup.org"
Received 101 bytes from 192.168.5.1#53 in 1 ms
Trying "download.rubackup.org.04-zabbix-amqp"
Host download.rubackup.org not found: 3(NXDOMAIN)
Received 129 bytes from 192.168.5.1#53 in 1 ms
coolcold@ubuntu-12:~/tmp$ host -t A download.rubackup.org. c.dns.gandi.net.
Using domain server:
Name: c.dns.gandi.net.
Address: 217.70.179.1#53
Aliases: 

Host download.rubackup.org. not found: 3(NXDOMAIN)

URL has been taken from http://www.rubackup.org/Download

**Comment by fdupoux** [comment]
Thanks for having reported this problem, it has been fixed.
