### ISSUE TITLE
What value for "snapshot_size" is reasonable

### ISSUE THREAD

**Issue by cmonty14** [fdupoux/rubackup#3]
Hi,
I'm planning to use rubackup for creating backups of my running OS.
This has a LVM with this config:
```
vllspdevsles12:~ # lvs
  LV   VG     Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root vg_sys -wi-ao----  12.46g
  swap vg_sys -wi-ao---- 864.00m
  tmp  vg_sys -wi-ao----   2.00g
  var  vg_sys -wi-ao----   3.00g
```
Questions:
- What is the recommended value for config parameter "snapshot_size"?
- What will happen to the snapshot of a Logical Volume after backup is created? Will this snapshot be deleted?

THX

**Comment by fdupoux** [comment]
The snapshot size correspond to the space allocated to store modifications on the LVM Logical Volume while there is the snapshot, hence during the time it takes to create the backup from the LVM Snapshot. So if you have a 12GB root LV and and say 5GB free in the Volume Group, you could allocate 2G so it can write up to 2GB duing that time. If the snapshot is too small the snapshot will be destroyed as soon as you write more than 2GB to the LV while the backup is being done, and the backup will fail. So it really depends on how much space is left in the VG and how much is being written to the original volume during the backup.
